apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: chiaretto-grafana
spec:
  config:
    auth.ldap:
      config_file: /etc/grafana-configmaps/ldap-config/ldap.toml
      enabled: true
    log:
      level: trace
      mode: console
  configMaps:
  - ldap-config
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  ingress:
    enabled: true
    hostname: "grafana.apps.ipi.chiaret.to"
