kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: grafana-operator-view
  namespace: chiaretto-monitoring
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups:
  - "integreatly.org"
  resources:
  - grafanas
  - grafanas/status
  - grafanas/finalizers
  - grafanadashboards
  - grafanadatasources
  - grafanadatasources/status
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
    - ""
  resources:
    - events
  verbs: ['create', 'patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator
  namespace: chiaretto-monitoring
roleRef:
  name: grafana-operator-view
  kind: ClusterRole
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: chiaretto-monitoring
