apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
data:
  ldap.toml: |
    [[servers]]
    host = "chiaretto-ad01.chiaret.to"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = false
    bind_dn = "CN=Administrator,CN=Users,DC=chiaretto,DC=home"
    bind_password = 'VMware1!'
    search_filter = "(cn=%s)"
    search_base_dns = ["cn=users,dc=chiaretto,dc=home"]
    [servers.attributes]
    name = "cn"
    surname = "sn"
    username = "cn"
    member_of = "memberOf"
    email =  "userPrincipalName"
    [[servers.group_mappings]]
    group_dn = "cn=OCP Admins,cn=Users,dc=chiaretto,dc=home"
    org_role = "Admin"
    org_id = 1
    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"
    org_id = 1
