{
 "title": "Custom",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "ETCD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Openshift Latest Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_job_status_start_time{namespace=\"ocp-backup-etcd\"} AND kube_job_status_succeeded{namespace=\"ocp-backup-etcd\"}) * 1000"
    }
   ]
  },
  {
   "title": "CPU Core Count & Allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Cores Used in Openshift",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(machine_cpu_cores)" }
     ]
    },
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      { "expr": "sum (machine_memory_bytes)" }
     ]
    },
    {
     "title": "Cores used by Masters",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=~\".*master.*\"})"
      }
     ]
    },
    {
     "title": "Cores use by Infra Nodes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=~\".*infra.*\"})"
      }
     ]
    },
    {
     "title": "Cores used by App Nodes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=~\".*worker.*\"})"
      }
     ]
    },
    {
     "title": "Master Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node=~\".*master.*\"})"
      }
     ]
    },
    {
     "title": "Infra Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node=~\".*infra.*\"})"
      }
     ]
    },
    {
     "title": "App Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node=~\".*worker.*\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU usage ",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\".*worker.*\"}[1m])) / sum(machine_cpu_cores{node=~\".*worker.*\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU Request Allocation - APP",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum ((kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\",node=~\".*worker.*\"})*1000)) / (sum(machine_cpu_cores{node=~\".*worker.*\"})*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_cpu_quota{node=~\".*worker.*\"})/100) / (sum(machine_cpu_cores{node=~\".*worker.*\"})*1000)  * 100 "
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\".*worker.*\"}) / sum(machine_memory_bytes{node=~\".*worker.*\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory Request Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (kube_pod_container_resource_requests_memory_bytes{node=~\".*worker.*\"})) / (sum(machine_memory_bytes{node=~\".*worker.*\"}))  * 100 "
      }
     ]
    },
    {
     "title": "Total Memory Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(container_spec_memory_limit_bytes{pod_name!=\"\",node=~\".*worker.*\"})) / (sum (machine_memory_bytes{node=~\".*worker.*\"})) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Masters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU usage ",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\".*master.*\"}[1m])) / sum(machine_cpu_cores{node=~\".*master.*\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU Request Allocation - MASTER",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum ((kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\",node=~\".*master.*\"})*1000)) / (sum(machine_cpu_cores{node=~\".*master.*\"})*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_cpu_quota{node=~\".*master.*\"})/100) / (sum(machine_cpu_cores{node=~\".*master.*\"})*1000)  * 100 "
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\".*master.*\"}) / sum(machine_memory_bytes{node=~\".*master.*\"}) * 100"
      }
     ]
    },
    {
     "title": "Memory Request Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (kube_pod_container_resource_requests_memory_bytes{node=~\".*master.*\"})) / (sum(machine_memory_bytes{node=~\".*master.*\"}))  * 100 "
      }
     ]
    },
    {
     "title": "Total Memory Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(container_spec_memory_limit_bytes{pod_name!=\"\",node=~\".*master.*\"})) / (sum (machine_memory_bytes{node=~\".*master.*\"})) * 100"
      }
     ]
    }
   ]
  },
  { "title": "Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod Limit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "1/((sum(machine_cpu_cores{node=~\".*worker.*\"})*10) / (sum (kube_pod_info{namespace!=\"default\",namespace!~\"openshift-.*\",created_by_kind!=\"<none>\"})))  * 100 "
    }
   ]
  },
  {
   "title": "Current number of Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_pod_info{namespace!=\"default\",namespace!~\"openshift-.*\",created_by_kind!=\"<none>\"})"
    }
   ]
  },
  {
   "title": "Project Quota Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) / (sum(machine_memory_bytes{node=~\".*worker.*\"}))  * 100 "
    }
   ]
  },
  {
   "title": "Project Quota Memory LImits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) / (sum(machine_memory_bytes{node=~\".*worker.*\"}))  * 100 "
    }
   ]
  },
  {
   "title": "Project Quota CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) / (sum(machine_cpu_cores{node=~\".*worker.*\"})) * 100 "
    }
   ]
  },
  {
   "title": "Project Quota CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) / (sum(machine_cpu_cores{node=~\".*worker.*\"})) * 100 "
    }
   ]
  }
 ]
}