kind: LDAPSyncConfig
apiVersion: v1
url: ldap://ad.chiaret.to:389
bindDN: CN=Administrator,CN=Users,DC=chiaretto,DC=home
bindPassword: 
  file: /root/bindpassword
insecure: true
activeDirectory:
    usersQuery:
        baseDN: "cn=users,dc=chiaretto,dc=home"
        scope: sub
        derefAliases: never
        filter: (objectclass=person)
        pageSize: 0
    userNameAttributes: [ sAMAccountName ]
    groupMembershipAttributes: [ memberOf ]
